# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Trapezoidal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Trapezoidal(object):
    def setupUi(self, Trapezoidal):
        Trapezoidal.setObjectName("Trapezoidal")
        Trapezoidal.resize(540, 379)
        self.centralwidget = QtWidgets.QWidget(Trapezoidal)
        self.centralwidget.setObjectName("centralwidget")
        Trapezoidal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Trapezoidal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 21))
        self.menubar.setObjectName("menubar")
        self.menuFunction = QtWidgets.QMenu(self.menubar)
        self.menuFunction.setObjectName("menuFunction")
        self.menuPoints = QtWidgets.QMenu(self.menubar)
        self.menuPoints.setObjectName("menuPoints")
        Trapezoidal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Trapezoidal)
        self.statusbar.setObjectName("statusbar")
        Trapezoidal.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFunction.menuAction())
        self.menubar.addAction(self.menuPoints.menuAction())

        self.retranslateUi(Trapezoidal)
        QtCore.QMetaObject.connectSlotsByName(Trapezoidal)

    def retranslateUi(self, Trapezoidal):
        _translate = QtCore.QCoreApplication.translate
        Trapezoidal.setWindowTitle(_translate("Trapezoidal", "MainWindow"))
        self.menuFunction.setTitle(_translate("Trapezoidal", "Function"))
        self.menuPoints.setTitle(_translate("Trapezoidal", "Points"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Trapezoidal = QtWidgets.QMainWindow()
    ui = Ui_Trapezoidal()
    ui.setupUi(Trapezoidal)
    Trapezoidal.show()
    sys.exit(app.exec_())
